= README

All the ledger's a stage, and the accounts in it merely players; +
They have their exits and their entrances +
Though the Accountant call them debits and credits. +
Money in transaction plays two acts, the first its addition, +
The second its complete negation. In bookkeeping, +
The double entry of a moment, at least two postings, must be made: +
Where money is privy to our deeds and misdeeds; +
Where usurers compound their interests with green eyeshade; +
Where Mammon whispers our avarice into complicity; +
Where post-capitalism derives chimerical things +
To advertise, exhorting us to sell and buy; +
And the economy drops the have nots into a crouch, +
And sets the have somes with a bubble precarity about them, +
And leaves the have-mosts helicoptering from one pillar to another, +
Hoarding their leverage and leveraging their hoard, +
The budgeting, the passion, and the syllables counted +
Until the balance of both creed and debt has been recorded all +
And the accounts are settled.
